/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs.cs2263;

import javafx.application.Application;   
import javafx.stage.Stage; 

public class App extends Application{
	

	public void start(Stage stage) throws Exception {stage.setTitle("whatever I need it to be");

		stage.show();
	}

	public static void main(String[] args) {
        Application.launch(args);
	}
}
